package com.chunkedge.extractor;

import java.util.Map;

/**
 * Maps Minecraft 26.x official (MojMap) names back to the legacy
 * (1.21.5-era Yarn) names used in the extracted JSON files.
 *
 * <p>ChunkEdge's generated Rust API (entity modules, tracked-data
 * components, status/animation enums) is built from these JSON keys, so
 * keeping the legacy names keeps the public API stable across the version
 * update. Only names Mojang actually changed are mapped; everything new
 * in 26.x keeps its official name.
 *
 * <p>Class mapping was derived by matching entity-type registry paths
 * (stable across versions) and children sets for abstract classes. Field
 * mapping was derived per class by wire-kind, default value, and name
 * similarity, with shifted/reused indexes resolved by hand against the
 * vanilla sources. Status/animation mapping is by numeric ID.
 */
public final class LegacyNames {

    private LegacyNames() {}

    /** Official class simple name -> legacy JSON key. */
    private static final Map<String, String> CLASS_NAMES = Map.ofEntries(
            Map.entry("AbstractArrow", "PersistentProjectileEntity"),
            Map.entry("AbstractBoat", "AbstractBoatEntity"),
            Map.entry("AbstractChestBoat", "AbstractChestBoatEntity"),
            Map.entry("AbstractChestedHorse", "AbstractDonkeyEntity"),
            Map.entry("AbstractCow", "AbstractCowEntity"),
            Map.entry("AbstractFish", "FishEntity"),
            Map.entry("AbstractGolem", "GolemEntity"),
            Map.entry("AbstractHorse", "AbstractHorseEntity"),
            Map.entry("AbstractHurtingProjectile", "ExplosiveProjectileEntity"),
            Map.entry("AbstractIllager", "IllagerEntity"),
            Map.entry("AbstractMinecart", "AbstractMinecartEntity"),
            Map.entry("AbstractMinecartContainer", "StorageMinecartEntity"),
            Map.entry("AbstractPiglin", "AbstractPiglinEntity"),
            Map.entry("AbstractSchoolingFish", "SchoolingFishEntity"),
            Map.entry("AbstractSkeleton", "AbstractSkeletonEntity"),
            Map.entry("AbstractThrownPotion", "PotionEntity"),
            Map.entry("AbstractVillager", "MerchantEntity"),
            Map.entry("AbstractWindCharge", "AbstractWindChargeEntity"),
            Map.entry("AgeableMob", "PassiveEntity"),
            Map.entry("AgeableWaterCreature", "WaterAnimalEntity"),
            Map.entry("Allay", "AllayEntity"),
            Map.entry("AmbientCreature", "AmbientEntity"),
            Map.entry("Animal", "AnimalEntity"),
            Map.entry("AreaEffectCloud", "AreaEffectCloudEntity"),
            Map.entry("Armadillo", "ArmadilloEntity"),
            Map.entry("ArmorStand", "ArmorStandEntity"),
            Map.entry("Arrow", "ArrowEntity"),
            Map.entry("Axolotl", "AxolotlEntity"),
            Map.entry("Bat", "BatEntity"),
            Map.entry("Bee", "BeeEntity"),
            Map.entry("Blaze", "BlazeEntity"),
            Map.entry("BlockDisplay", "BlockDisplayEntity"),
            Map.entry("Boat", "BoatEntity"),
            Map.entry("Bogged", "BoggedEntity"),
            Map.entry("Breeze", "BreezeEntity"),
            Map.entry("BreezeWindCharge", "BreezeWindChargeEntity"),
            Map.entry("Camel", "CamelEntity"),
            Map.entry("Cat", "CatEntity"),
            Map.entry("CaveSpider", "CaveSpiderEntity"),
            Map.entry("ChestBoat", "ChestBoatEntity"),
            Map.entry("ChestRaft", "ChestRaftEntity"),
            Map.entry("Chicken", "ChickenEntity"),
            Map.entry("Cod", "CodEntity"),
            Map.entry("Cow", "CowEntity"),
            Map.entry("Creaking", "CreakingEntity"),
            Map.entry("Creeper", "CreeperEntity"),
            Map.entry("Display", "DisplayEntity"),
            Map.entry("Dolphin", "DolphinEntity"),
            Map.entry("Donkey", "DonkeyEntity"),
            Map.entry("DragonFireball", "DragonFireballEntity"),
            Map.entry("Drowned", "DrownedEntity"),
            Map.entry("ElderGuardian", "ElderGuardianEntity"),
            Map.entry("EndCrystal", "EndCrystalEntity"),
            Map.entry("EnderDragon", "EnderDragonEntity"),
            Map.entry("EnderMan", "EndermanEntity"),
            Map.entry("Endermite", "EndermiteEntity"),
            Map.entry("Evoker", "EvokerEntity"),
            Map.entry("EvokerFangs", "EvokerFangsEntity"),
            Map.entry("ExperienceOrb", "ExperienceOrbEntity"),
            Map.entry("EyeOfEnder", "EyeOfEnderEntity"),
            Map.entry("Fireball", "AbstractFireballEntity"),
            Map.entry("FishingHook", "FishingBobberEntity"),
            Map.entry("Fox", "FoxEntity"),
            Map.entry("Frog", "FrogEntity"),
            Map.entry("Ghast", "GhastEntity"),
            Map.entry("Giant", "GiantEntity"),
            Map.entry("GlowItemFrame", "GlowItemFrameEntity"),
            Map.entry("GlowSquid", "GlowSquidEntity"),
            Map.entry("Goat", "GoatEntity"),
            Map.entry("Guardian", "GuardianEntity"),
            Map.entry("HangingEntity", "AbstractDecorationEntity"),
            Map.entry("Hoglin", "HoglinEntity"),
            Map.entry("Horse", "HorseEntity"),
            Map.entry("Husk", "HuskEntity"),
            Map.entry("Illusioner", "IllusionerEntity"),
            Map.entry("Interaction", "InteractionEntity"),
            Map.entry("IronGolem", "IronGolemEntity"),
            Map.entry("ItemDisplay", "ItemDisplayEntity"),
            Map.entry("ItemFrame", "ItemFrameEntity"),
            Map.entry("LargeFireball", "FireballEntity"),
            Map.entry("LeashFenceKnotEntity", "LeashKnotEntity"),
            Map.entry("LightningBolt", "LightningEntity"),
            Map.entry("Llama", "LlamaEntity"),
            Map.entry("LlamaSpit", "LlamaSpitEntity"),
            Map.entry("MagmaCube", "MagmaCubeEntity"),
            Map.entry("Marker", "MarkerEntity"),
            Map.entry("Minecart", "MinecartEntity"),
            Map.entry("MinecartChest", "ChestMinecartEntity"),
            Map.entry("MinecartCommandBlock", "CommandBlockMinecartEntity"),
            Map.entry("MinecartFurnace", "FurnaceMinecartEntity"),
            Map.entry("MinecartHopper", "HopperMinecartEntity"),
            Map.entry("MinecartSpawner", "SpawnerMinecartEntity"),
            Map.entry("MinecartTNT", "TntMinecartEntity"),
            Map.entry("Mob", "MobEntity"),
            Map.entry("Monster", "HostileEntity"),
            Map.entry("Mule", "MuleEntity"),
            Map.entry("MushroomCow", "MooshroomEntity"),
            Map.entry("Ocelot", "OcelotEntity"),
            Map.entry("OminousItemSpawner", "OminousItemSpawnerEntity"),
            Map.entry("Painting", "PaintingEntity"),
            Map.entry("Panda", "PandaEntity"),
            Map.entry("Parrot", "ParrotEntity"),
            Map.entry("PathfinderMob", "PathAwareEntity"),
            Map.entry("PatrollingMonster", "PatrolEntity"),
            Map.entry("Phantom", "PhantomEntity"),
            Map.entry("Pig", "PigEntity"),
            Map.entry("Piglin", "PiglinEntity"),
            Map.entry("PiglinBrute", "PiglinBruteEntity"),
            Map.entry("Pillager", "PillagerEntity"),
            Map.entry("Player", "PlayerEntity"),
            Map.entry("PolarBear", "PolarBearEntity"),
            Map.entry("PrimedTnt", "TntEntity"),
            Map.entry("Projectile", "ProjectileEntity"),
            Map.entry("Pufferfish", "PufferfishEntity"),
            Map.entry("Rabbit", "RabbitEntity"),
            Map.entry("Raft", "RaftEntity"),
            Map.entry("Raider", "RaiderEntity"),
            Map.entry("Ravager", "RavagerEntity"),
            Map.entry("Salmon", "SalmonEntity"),
            Map.entry("Sheep", "SheepEntity"),
            Map.entry("ShoulderRidingEntity", "TameableShoulderEntity"),
            Map.entry("Shulker", "ShulkerEntity"),
            Map.entry("ShulkerBullet", "ShulkerBulletEntity"),
            Map.entry("Silverfish", "SilverfishEntity"),
            Map.entry("Skeleton", "SkeletonEntity"),
            Map.entry("SkeletonHorse", "SkeletonHorseEntity"),
            Map.entry("Slime", "SlimeEntity"),
            Map.entry("SmallFireball", "SmallFireballEntity"),
            Map.entry("Sniffer", "SnifferEntity"),
            Map.entry("SnowGolem", "SnowGolemEntity"),
            Map.entry("Snowball", "SnowballEntity"),
            Map.entry("SpectralArrow", "SpectralArrowEntity"),
            Map.entry("SpellcasterIllager", "SpellcastingIllagerEntity"),
            Map.entry("Spider", "SpiderEntity"),
            Map.entry("Squid", "SquidEntity"),
            Map.entry("Stray", "StrayEntity"),
            Map.entry("Strider", "StriderEntity"),
            Map.entry("Tadpole", "TadpoleEntity"),
            Map.entry("TamableAnimal", "TameableEntity"),
            Map.entry("TextDisplay", "TextDisplayEntity"),
            Map.entry("ThrowableItemProjectile", "ThrownItemEntity"),
            Map.entry("ThrowableProjectile", "ThrownEntity"),
            Map.entry("ThrownEgg", "EggEntity"),
            Map.entry("ThrownEnderpearl", "EnderPearlEntity"),
            Map.entry("ThrownExperienceBottle", "ExperienceBottleEntity"),
            Map.entry("ThrownLingeringPotion", "LingeringPotionEntity"),
            Map.entry("ThrownSplashPotion", "SplashPotionEntity"),
            Map.entry("ThrownTrident", "TridentEntity"),
            Map.entry("TraderLlama", "TraderLlamaEntity"),
            Map.entry("TropicalFish", "TropicalFishEntity"),
            Map.entry("Turtle", "TurtleEntity"),
            Map.entry("Vex", "VexEntity"),
            Map.entry("Villager", "VillagerEntity"),
            Map.entry("Vindicator", "VindicatorEntity"),
            Map.entry("WanderingTrader", "WanderingTraderEntity"),
            Map.entry("Warden", "WardenEntity"),
            Map.entry("WaterAnimal", "WaterAnimalEntity"),
            Map.entry("WindCharge", "WindChargeEntity"),
            Map.entry("Witch", "WitchEntity"),
            Map.entry("WitherBoss", "WitherEntity"),
            Map.entry("WitherSkeleton", "WitherSkeletonEntity"),
            Map.entry("WitherSkull", "WitherSkullEntity"),
            Map.entry("Wolf", "WolfEntity"),
            Map.entry("Zoglin", "ZoglinEntity"),
            Map.entry("Zombie", "ZombieEntity"),
            Map.entry("ZombieHorse", "ZombieHorseEntity"),
            Map.entry("ZombieVillager", "ZombieVillagerEntity"),
            Map.entry("ZombifiedPiglin", "ZombifiedPiglinEntity")    );

    /** Official Class.field -> legacy field name. */
    private static final Map<String, String> FIELD_NAMES = Map.ofEntries(
            Map.entry("AbstractCubeMob.id_size", "slime_size"),
            Map.entry("AgeableMob.data_baby_id", "child"),
            Map.entry("Allay.data_can_duplicate", "can_duplicate"),
            Map.entry("Allay.data_dancing", "dancing"),
            Map.entry("AreaEffectCloud.data_particle", "particle"),
            Map.entry("AreaEffectCloud.data_radius", "radius"),
            Map.entry("AreaEffectCloud.data_waiting", "waiting"),
            Map.entry("Armadillo.armadillo_state", "state"),
            Map.entry("ArmorStand.data_body_pose", "tracker_body_rotation"),
            Map.entry("ArmorStand.data_client_flags", "armor_stand_flags"),
            Map.entry("ArmorStand.data_head_pose", "tracker_head_rotation"),
            Map.entry("ArmorStand.data_left_arm_pose", "tracker_left_arm_rotation"),
            Map.entry("ArmorStand.data_left_leg_pose", "tracker_left_leg_rotation"),
            Map.entry("ArmorStand.data_right_arm_pose", "tracker_right_arm_rotation"),
            Map.entry("ArmorStand.data_right_leg_pose", "tracker_right_leg_rotation"),
            Map.entry("Arrow.id_effect_color", "color"),
            Map.entry("Axolotl.data_playing_dead", "playing_dead"),
            Map.entry("Axolotl.data_variant", "variant"),
            Map.entry("AbstractArrow.id_flags", "projectile_flags"),
            Map.entry("AbstractHorse.data_id_flags", "horse_flags"),
            Map.entry("Bat.data_id_flags", "bat_flags"),
            Map.entry("Bee.data_flags_id", "bee_flags"),
            Map.entry("Blaze.data_flags_id", "blaze_flags"),
            Map.entry("BlockDisplay.data_block_state_id", "block_state"),
            Map.entry("Bogged.data_sheared", "sheared"),
            Map.entry("Camel.dash", "dashing"),
            Map.entry("Camel.last_pose_change_tick", "last_pose_tick"),
            Map.entry("Cat.data_collar_color", "collar_color"),
            Map.entry("Cat.data_variant_id", "cat_variant"),
            Map.entry("Cat.is_lying", "in_sleeping_pose"),
            Map.entry("Cat.relax_state_one", "head_down"),
            Map.entry("Chicken.data_variant_id", "variant"),
            Map.entry("Cow.data_variant_id", "variant"),
            Map.entry("Creaking.can_move", "unrooted"),
            Map.entry("Creaking.is_active", "active"),
            Map.entry("Creaking.is_tearing_down", "crumbling"),
            Map.entry("Creeper.data_is_ignited", "ignited"),
            Map.entry("Creeper.data_is_powered", "charged"),
            Map.entry("Creeper.data_swell_dir", "fuse_speed"),
            Map.entry("Display.data_billboard_render_constraints_id", "billboard"),
            Map.entry("Display.data_brightness_override_id", "brightness"),
            Map.entry("Display.data_glow_color_override_id", "glow_color_override"),
            Map.entry("Display.data_height_id", "height"),
            Map.entry("Display.data_left_rotation_id", "left_rotation"),
            Map.entry("Display.data_pos_rot_interpolation_duration_id", "teleport_duration"),
            Map.entry("Display.data_right_rotation_id", "right_rotation"),
            Map.entry("Display.data_scale_id", "scale"),
            Map.entry("Display.data_shadow_radius_id", "shadow_radius"),
            Map.entry("Display.data_shadow_strength_id", "shadow_strength"),
            Map.entry("Display.data_transformation_interpolation_duration_id", "interpolation_duration"),
            Map.entry("Display.data_transformation_interpolation_start_delta_ticks_id", "start_interpolation"),
            Map.entry("Display.data_translation_id", "translation"),
            Map.entry("Display.data_view_range_id", "view_range"),
            Map.entry("Display.data_width_id", "width"),
            Map.entry("Dolphin.got_fish", "has_fish"),
            Map.entry("Dolphin.moistness_level", "moistness"),
            Map.entry("EndCrystal.data_beam_target", "beam_target"),
            Map.entry("EndCrystal.data_show_bottom", "show_bottom"),
            Map.entry("EnderDragon.data_phase", "phase_type"),
            Map.entry("EnderMan.data_carry_state", "carried_block"),
            Map.entry("EnderMan.data_creepy", "angry"),
            Map.entry("EnderMan.data_stared_at", "provoked"),
            Map.entry("Entity.data_air_supply_id", "air"),
            Map.entry("Entity.data_custom_name", "custom_name"),
            Map.entry("Entity.data_custom_name_visible", "name_visible"),
            Map.entry("Entity.data_no_gravity", "no_gravity"),
            Map.entry("Entity.data_pose", "pose"),
            Map.entry("Entity.data_shared_flags_id", "flags"),
            Map.entry("Entity.data_silent", "silent"),
            Map.entry("Entity.data_ticks_frozen", "frozen_ticks"),
            Map.entry("ExperienceOrb.data_value", "value"),
            Map.entry("EyeOfEnder.data_item_stack", "item"),
            Map.entry("FallingBlockEntity.data_start_pos", "block_pos"),
            Map.entry("Fireball.data_item_stack", "item"),
            Map.entry("FireworkRocketEntity.data_attached_to_target", "shooter_entity_id"),
            Map.entry("FireworkRocketEntity.data_id_fireworks_item", "item"),
            Map.entry("FireworkRocketEntity.data_shot_at_angle", "shot_at_angle"),
            Map.entry("FishingHook.data_biting", "caught_fish"),
            Map.entry("FishingHook.data_hooked_entity", "hook_entity_id"),
            Map.entry("Fox.data_flags_id", "fox_flags"),
            Map.entry("Fox.data_trusted_id_0", "owner"),
            Map.entry("Fox.data_trusted_id_1", "other_trusted"),
            Map.entry("Fox.data_type_id", "variant"),
            Map.entry("Frog.data_tongue_target_id", "target"),
            Map.entry("Frog.data_variant_id", "variant"),
            Map.entry("Ghast.data_is_charging", "shooting"),
            Map.entry("GlowSquid.data_dark_ticks_remaining", "dark_ticks_remaining"),
            Map.entry("Goat.data_has_left_horn", "left_horn"),
            Map.entry("Goat.data_has_right_horn", "right_horn"),
            Map.entry("Goat.data_is_screaming_goat", "screaming"),
            Map.entry("Guardian.data_id_attack_target", "beam_target_id"),
            Map.entry("Horse.data_id_type_variant", "variant"),
            Map.entry("Interaction.data_height_id", "height"),
            Map.entry("Interaction.data_response_id", "response"),
            Map.entry("Interaction.data_width_id", "width"),
            Map.entry("IronGolem.data_flags_id", "iron_golem_flags"),
            Map.entry("ItemDisplay.data_item_display_id", "item_display"),
            Map.entry("ItemDisplay.data_item_stack_id", "item"),
            Map.entry("ItemEntity.data_item", "stack"),
            Map.entry("ItemFrame.data_item", "item_stack"),
            Map.entry("ItemFrame.data_rotation", "rotation"),
            Map.entry("LivingEntity.data_arrow_count_id", "stuck_arrow_count"),
            Map.entry("LivingEntity.data_effect_ambience_id", "potion_swirls_ambient"),
            Map.entry("LivingEntity.data_effect_particles", "potion_swirls"),
            Map.entry("LivingEntity.data_health_id", "health"),
            Map.entry("LivingEntity.data_living_entity_flags", "living_flags"),
            Map.entry("LivingEntity.data_stinger_count_id", "stinger_count"),
            Map.entry("LivingEntity.sleeping_pos_id", "sleeping_position"),
            Map.entry("Llama.data_strength_id", "strength"),
            Map.entry("Llama.data_variant_id", "variant"),
            Map.entry("MinecartCommandBlock.data_id_command_name", "command"),
            Map.entry("MinecartCommandBlock.data_id_last_output", "last_output"),
            Map.entry("MinecartFurnace.data_id_fuel", "lit"),
            Map.entry("Mob.data_mob_flags_id", "mob_flags"),
            Map.entry("MushroomCow.data_type", "variant"),
            Map.entry("Ocelot.data_trusting", "trusting"),
            Map.entry("OminousItemSpawner.data_item", "item"),
            Map.entry("Painting.data_painting_variant_id", "variant"),
            Map.entry("Panda.data_id_flags", "panda_flags"),
            Map.entry("Panda.eat_counter", "eating_ticks"),
            Map.entry("Panda.hidden_gene_id", "hidden_gene"),
            Map.entry("Panda.main_gene_id", "main_gene"),
            Map.entry("Panda.sneeze_counter", "sneeze_progress"),
            Map.entry("Panda.unhappy_counter", "ask_for_bamboo_ticks"),
            Map.entry("Parrot.data_variant_id", "variant"),
            Map.entry("Phantom.id_size", "size"),
            Map.entry("Pig.data_boost_time", "boost_time"),
            Map.entry("Pig.data_variant_id", "variant"),
            Map.entry("Piglin.data_baby_id", "baby"),
            Map.entry("Piglin.data_is_charging_crossbow", "charging"),
            Map.entry("Piglin.data_is_dancing", "dancing"),
            Map.entry("Pillager.is_charging_crossbow", "charging"),
            Map.entry("Player.data_player_absorption_id", "absorption_amount"),
            Map.entry("Player.data_score_id", "score"),
            Map.entry("PolarBear.data_standing_id", "warning"),
            Map.entry("PrimedTnt.data_block_state_id", "block_state"),
            Map.entry("PrimedTnt.data_fuse_id", "fuse"),
            Map.entry("Rabbit.data_type_id", "variant"),
            Map.entry("Raider.is_celebrating", "celebrating"),
            Map.entry("Salmon.data_type", "variant"),
            Map.entry("Sheep.data_wool_id", "color"),
            Map.entry("Shulker.data_attach_face_id", "attached_face"),
            Map.entry("Shulker.data_color_id", "color"),
            Map.entry("Shulker.data_peek_id", "peek_amount"),
            Map.entry("Skeleton.data_stray_conversion_id", "converting"),
            Map.entry("Sniffer.data_drop_seed_at_tick", "finish_dig_time"),
            Map.entry("Sniffer.data_state", "state"),
            Map.entry("SnowGolem.data_pumpkin_id", "snow_golem_flags"),
            Map.entry("SpellcasterIllager.data_spell_casting_id", "spell"),
            Map.entry("Spider.data_flags_id", "spider_flags"),
            Map.entry("Strider.data_boost_time", "boost_time"),
            Map.entry("Strider.data_suffocating", "cold"),
            Map.entry("TamableAnimal.data_flags_id", "tameable_flags"),
            Map.entry("TamableAnimal.data_owneruuid_id", "owner_uuid"),
            Map.entry("TextDisplay.data_background_color_id", "background"),
            Map.entry("TextDisplay.data_line_width_id", "line_width"),
            Map.entry("TextDisplay.data_style_flags_id", "text_display_flags"),
            Map.entry("TextDisplay.data_text_id", "text"),
            Map.entry("TextDisplay.data_text_opacity_id", "text_opacity"),
            Map.entry("ThrowableItemProjectile.data_item_stack", "item"),
            Map.entry("ThrownTrident.id_foil", "enchanted"),
            Map.entry("ThrownTrident.id_loyalty", "loyalty"),
            Map.entry("TropicalFish.data_id_type_variant", "variant"),
            Map.entry("Turtle.has_egg", "has_egg"),
            Map.entry("Turtle.laying_egg", "digging_sand"),
            Map.entry("VehicleEntity.data_id_damage", "damage_wobble_strength"),
            Map.entry("VehicleEntity.data_id_hurt", "damage_wobble_ticks"),
            Map.entry("VehicleEntity.data_id_hurtdir", "damage_wobble_side"),
            Map.entry("Vex.data_flags_id", "vex_flags"),
            Map.entry("Villager.data_villager_data", "villager_data"),
            Map.entry("Warden.client_anger_level", "anger"),
            Map.entry("Witch.data_using_item", "drinking"),
            Map.entry("WitherBoss.data_id_inv", "invul_timer"),
            Map.entry("WitherBoss.data_target_a", "tracked_entity_id_1"),
            Map.entry("WitherBoss.data_target_b", "tracked_entity_id_2"),
            Map.entry("WitherSkull.data_dangerous", "charged"),
            Map.entry("Wolf.data_collar_color", "collar_color"),
            Map.entry("Wolf.data_interested_id", "begging"),
            Map.entry("Wolf.data_sound_variant_id", "sound_variant"),
            Map.entry("Wolf.data_variant_id", "variant"),
            Map.entry("Zoglin.data_baby_id", "baby"),
            Map.entry("Zombie.data_baby_id", "baby"),
            Map.entry("Zombie.data_drowned_conversion_id", "converting_in_water"),
            Map.entry("Zombie.data_special_type_id", "zombie_type"),
            Map.entry("ZombieVillager.data_converting_id", "converting"),
            Map.entry("ZombieVillager.data_villager_data", "villager_data")    );

    /** Official Class.field -> legacy type string. */
    private static final Map<String, String> FIELD_TYPES = Map.ofEntries(
            Map.entry("AbstractCubeMob.id_size", "integer"),
            Map.entry("Armadillo.armadillo_state", "armadillo_state"),
            Map.entry("Cat.is_lying", "boolean"),
            Map.entry("Cat.relax_state_one", "boolean"),
            Map.entry("Fox.data_trusted_id_0", "lazy_entity_reference"),
            Map.entry("Fox.data_trusted_id_1", "lazy_entity_reference"),
            Map.entry("Panda.eat_counter", "integer"),
            Map.entry("Player.data_player_absorption_id", "float"),
            Map.entry("Player.data_score_id", "integer"),
            Map.entry("Turtle.has_egg", "boolean"),
            Map.entry("Turtle.laying_egg", "boolean"),
            Map.entry("WitherBoss.data_id_inv", "integer")    );

    /** Official (lowercased) status key -> legacy key, by stable numeric ID. */
    private static final Map<String, String> STATUS_NAMES = Map.ofEntries(
        Map.entry("jump", "add_sprinting_particles_or_reset_spawner_minecart_spawn_delay"),
        Map.entry("death", "play_death_sound_or_add_projectile_hit_particles"),
        Map.entry("start_attacking", "play_attack_sound"),
        Map.entry("stop_attacking", "stop_attack"),
        Map.entry("taming_failed", "add_negative_player_reaction_particles"),
        Map.entry("taming_succeeded", "add_positive_player_reaction_particles"),
        Map.entry("shake_wetness", "shake_off_water"),
        Map.entry("use_item_complete", "consume_item"),
        Map.entry("eat_grass", "set_sheep_eat_grass_timer_or_prime_tnt_minecart"),
        Map.entry("offer_flower", "look_at_villager"),
        Map.entry("love_hearts", "add_villager_heart_particles"),
        Map.entry("villager_angry", "add_villager_angry_particles"),
        Map.entry("villager_happy", "add_villager_happy_particles"),
        Map.entry("witch_hat_magic", "add_witch_particles"),
        Map.entry("zombie_converting", "play_cure_zombie_villager_sound"),
        Map.entry("fireworks_explode", "explode_firework_client"),
        Map.entry("in_love_hearts", "add_breeding_particles"),
        Map.entry("squid_anim_synch", "reset_squid_thrust_timer"),
        Map.entry("silverfish_merge_anim", "play_spawn_effects"),
        Map.entry("guardian_attack_sound", "play_guardian_attack_sound"),
        Map.entry("reduced_debug_info", "use_reduced_debug_info"),
        Map.entry("full_debug_info", "use_full_debug_info"),
        Map.entry("permission_level_all", "set_op_level_0"),
        Map.entry("permission_level_moderators", "set_op_level_1"),
        Map.entry("permission_level_gamemasters", "set_op_level_2"),
        Map.entry("permission_level_admins", "set_op_level_3"),
        Map.entry("permission_level_owners", "set_op_level_4"),
        Map.entry("fishing_rod_reel_in", "pull_hooked_entity"),
        Map.entry("armorstand_wobble", "hit_armor_stand"),
        Map.entry("stop_offer_flower", "stop_looking_at_villager"),
        Map.entry("protected_from_death", "use_totem_of_undying"),
        Map.entry("dolphin_looking_for_treasure", "add_dolphin_happy_villager_particles"),
        Map.entry("ravager_stunned", "stun_ravager"),
        Map.entry("trusting_failed", "tame_ocelot_failed"),
        Map.entry("trusting_succeeded", "tame_ocelot_success"),
        Map.entry("villager_sweat", "add_splash_particles"),
        Map.entry("fox_eat", "create_eating_particles"),
        Map.entry("teleport", "add_portal_particles"),
        Map.entry("mainhand_break", "break_mainhand"),
        Map.entry("offhand_break", "break_offhand"),
        Map.entry("head_break", "break_head"),
        Map.entry("chest_break", "break_chest"),
        Map.entry("legs_break", "break_legs"),
        Map.entry("feet_break", "break_feet"),
        Map.entry("honey_slide", "drip_honey"),
        Map.entry("honey_jump", "drip_rich_honey"),
        Map.entry("cancel_shake_wetness", "reset_wolf_shake"),
        Map.entry("start_ram", "prepare_ram"),
        Map.entry("end_ram", "finish_ram"),
        Map.entry("poof", "add_death_particles"),
        Map.entry("tendrils_shiver", "ears_twitch"),
        Map.entry("sonic_charge", "sonic_boom"),
        Map.entry("sniffer_digging_sound", "start_digging"),
        Map.entry("armadillo_peek", "peeking"),
        Map.entry("body_break", "break_body"),
        Map.entry("shake", "invulnerable_creaking_hit"),
        Map.entry("drown_particles", "add_bubble_particles"),
        Map.entry("saddle_break", "break_saddle"),
        Map.entry("critical_hit", "crit"),
        Map.entry("magic_critical_hit", "enchanted_hit")    );

    public static String className(String official) {
        return CLASS_NAMES.getOrDefault(official, official);
    }

    public static String fieldName(String ownerClass, String officialField) {
        return FIELD_NAMES.getOrDefault(ownerClass + "." + officialField, officialField);
    }

    /** Legacy type string override, or {@code null} to keep the computed one. */
    public static String fieldTypeOrNull(String ownerClass, String officialField) {
        return FIELD_TYPES.get(ownerClass + "." + officialField);
    }

    /** Official (lowercased) animation key -> legacy key, by stable numeric ID. */
    private static final Map<String, String> ANIMATION_NAMES = Map.ofEntries(
        Map.entry("critical_hit", "crit"),
        Map.entry("magic_critical_hit", "enchanted_hit")
    );

    public static String statusName(String official) {
        return STATUS_NAMES.getOrDefault(official, official);
    }

    public static String animationName(String official) {
        return ANIMATION_NAMES.getOrDefault(official, official);
    }
}
